language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
  - "npm install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
  - "npm prune"
script:
  - "npm run test"
  - "npm run lint"
after_success:
  - "npm run coverage:codecov"
  - "npm run coverage:coveralls"
  - "npm run coverage:codacy"
  - if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run publish; fi
